from api import *

class TextToImage(someService):
    title = " ::: Text To Image :::"
    name = "TextToImage"
    iconURL = "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
    welcome = "Welcome to TextToImage Service! \n any thing you send here will turn into an image generated by ai"
    sessions = {}
    
    
def on_init_group(self, groupUID, *args, **kwargs ):

    self._api.send(self.Welcome)
    # self._api.sendPoll(groupUID, self.rootPoll)
    # send welcome
    pass 
    print("@@@@@@@@@@ text2image group init", groupUID, args, kwargs)



def on_incoming(self, data:incomingEvent, *args, **kwargs):
    # if data.eventType == "poll":
    print("!!!!!!!!!!!!!!!",data, args, kwargs)
    self._api.send(data.origin, "https://www.google.com/search?q="+str(data.data))
    print("::::::::::::::::::::::::: DONE text2image INCOMING")
    